zmiany stałe i adnotacje
Arkinefed/pio_git_rhymers pull request #1
Opened 2022-04-20 07:46 UTC by JuliaBalcer

2022-04-20 07:46 UTC, JuliaBalcer commented
lab 1.4 stałe i adnotacje

2022-04-20 07:56 UTC, Arkinefed commented
brak zmian w plikach z kodem

2022-04-20 07:56 UTC, Arkinefed commented
dodano automatycznie generowane pliki projektu

2022-05-01 15:45 UTC, JuliaBalcer commented
> brak zmian w plikach z kodem

poprawione

2022-05-01 15:48 UTC, JuliaBalcer commented
> dodano automatycznie generowane pliki projektu

poprawione

2022-05-02 18:30 UTC, Arkinefed commented
-w klasie DefaultCountingOutRhymer jeszcze jedna zmienna powinna być oznaczona jako final
-brak słowa kluczowego final w klasie Node

2022-05-02 18:32 UTC, Arkinefed commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> -	public int total = -1;
pole total powinno być inicjalizowane za pomocą stałej

2022-05-02 18:34 UTC, Arkinefed commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	public static final int EMPTY_VALUE = -5;
żadna z wartości, które zostały zastąpione nie była równa -5

2022-05-02 18:39 UTC, Arkinefed commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> +	private static final int NUMBERS_SIZE = 12;
stała określona tutaj przez NUMBERS_SIZE bardziej określa maksymalny rozmiar

2022-05-02 18:40 UTC, Arkinefed requested changes
kod nadal potrzebuje zmian

2022-05-03 17:04 UTC, JuliaBalcer commented on src/main/java/edu/kis/vh/nursery/DefaultCountingOutRhymer.java
> -	public int total = -1;
zrobione

2022-05-03 17:05 UTC, JuliaBalcer commented
> -w klasie DefaultCountingOutRhymer jeszcze jedna zmienna powinna być oznaczona jako final -brak słowa kluczowego final w klasie Node

zrobione

2022-05-03 17:05 UTC, JuliaBalcer commented
> kod nadal potrzebuje zmian

gotowe

2022-05-03 20:53 UTC, Arkinefed approved these changes
wszystko w porządku

2022-05-03 20:54 UTC, merged